/**
 * Localized UI strings for the Production Tracker visual (English + Hungarian).
 */
export type Language = "en" | "hu";

interface Strings {
    title: string;
    allShifts: string;
    allLines: string;
    allLocations: string;
    allProducts: string;
    allCategories: string;
    from: string;
    to: string;
    productionOverview: string;
    weeklySummary: string;
    produced: string;
    dailyTarget: string;
    belowTarget: string;
    fttLoss: string;
    scrap: string;
    downtime: string;
    openTime: string;
    runTime: string;
    planned: string;
    unplanned: string;
    oee: string;
    availability: string;
    quality: string;
    performance: string;
    minutes: string;
    pcs: string;
    noData: string;
    machine: string;
    light: string;
    dark: string;
    expand: string;
    collapse: string;
    toggleOee: string;
    tableView: string;
    tileView: string;
    oeeView: string;
    colProduct: string;
    colCycle: string;
    colProduced: string;
    colFtt: string;
    colScrap: string;
    colDowntimeCodes: string;
    colDowntimeMin: string;
    colOpenTime: string;
    colTarget: string;
    colFill: string;
    total: string;
    fulfillment: string;
    cycleTime: string;
    machineBreakdown: string;
    allMachines: string;
    // shift settings panel
    settings: string;
    shiftSchedule: string;
    shiftLength: string;
    shiftsPerDay: string;
    workingDays: string;
    plannedStop: string;
    plannedStops: string;
    summary: string;
    shiftTotal: string;
    plannedStopTotal: string;
    baseOpenTime: string;
    days: string;
    shifts: string;
    shiftCount: string;
    custom: string;
    // report
    report: string;
    dailyReport: string;
    productionReport: string;
    overallStatus: string;
    onTarget: string;
    attention: string;
    critical: string;
    onTargetLines: string;
    belowLines: string;
    totalProduced: string;
    plan: string;
    planFulfillment: string;
    scrapRate: string;
    perMachine: string;
    linePerformance: string;
    line: string;
    autoGenerated: string;
    // license banner (v5.3.7)
    licenseRequired: string;
    licenseDescription: string;
    startTrial: string;
}

const EN: Strings = {
    title: "Production Tracker",
    allShifts: "All shifts", allLines: "All lines", allLocations: "All locations",
    allProducts: "All products", allCategories: "All categories",
    from: "From", to: "To",
    productionOverview: "Production Overview", weeklySummary: "Summary",
    produced: "Produced", dailyTarget: "Daily Target", belowTarget: "Below target",
    fttLoss: "FTT Loss", scrap: "Scrap", downtime: "Downtime", openTime: "Open Time", runTime: "Run Time",
    planned: "Planned", unplanned: "Unplanned",
    oee: "OEE", availability: "Availability", quality: "Quality", performance: "Performance",
    minutes: "min", pcs: "pcs", noData: "Add data fields to see the production overview.", machine: "Machine",
    light: "☀ Light", dark: "🌙 Dark", expand: "▼ Expand", collapse: "▲ Collapse", toggleOee: "OEE",
    tableView: "Table", tileView: "Tiles", oeeView: "OEE",
    colProduct: "Product", colCycle: "Cycle", colProduced: "Produced", colFtt: "FTT Loss",
    colScrap: "Scrap", colDowntimeCodes: "Downtime Codes", colDowntimeMin: "Downtime min",
    colOpenTime: "Open Time", colTarget: "Target", colFill: "Fill %",
    total: "Total", fulfillment: "Fulfillment", cycleTime: "Cycle Time",
    machineBreakdown: "Machine OEE breakdown", allMachines: "All Machines",
    settings: "⚙ Shift settings", shiftSchedule: "Shift Schedule", shiftLength: "Shift length",
    shiftsPerDay: "Shifts / day", workingDays: "Working days / week", plannedStop: "Planned stop / shift",
    plannedStops: "Planned Stops",
    summary: "Summary", shiftTotal: "Shift total", plannedStopTotal: "Total planned stop",
    baseOpenTime: "Base Open Time", days: "days", shifts: "shifts",
    shiftCount: "Shift count", custom: "Custom (min)",
    report: "📊 Report", dailyReport: "Daily Report", productionReport: "Production Report",
    overallStatus: "Overall Status", onTarget: "On Target", attention: "Attention", critical: "Critical",
    onTargetLines: "lines on target", belowLines: "lines below target", totalProduced: "Total Produced",
    plan: "Plan", planFulfillment: "Plan Fulfillment", scrapRate: "scrap rate", perMachine: "min/line",
    linePerformance: "Line Performance", line: "Line", autoGenerated: "Auto-generated report",
    licenseRequired: "Editor license required",
    licenseDescription: "Viewers always see the visual for free. Only editors need a license to change settings.",
    startTrial: "Start 30-day free trial"
};

const HU: Strings = {
    title: "Production Tracker",
    allShifts: "Összes műszak", allLines: "Összes vonal", allLocations: "Összes helyszín",
    allProducts: "Összes termék", allCategories: "Összes kategória",
    from: "Tól", to: "Ig",
    productionOverview: "Termelési áttekintés", weeklySummary: "Összesítés",
    produced: "Legyártott", dailyTarget: "Napi cél", belowTarget: "Cél alatt",
    fttLoss: "FTT veszteség", scrap: "Selejt", downtime: "Állásidő", openTime: "Nyitott idő", runTime: "Futási idő",
    planned: "Tervezett", unplanned: "Nem tervezett",
    oee: "OEE", availability: "Rendelkezésre állás", quality: "Minőség", performance: "Teljesítmény",
    minutes: "perc", pcs: "db", noData: "Húzz be adatmezőket a termelési áttekintéshez.", machine: "Gép",
    light: "☀ Világos", dark: "🌙 Sötét", expand: "▼ Kinyit", collapse: "▲ Összecsuk", toggleOee: "OEE",
    tableView: "Táblázat", tileView: "Kártyák", oeeView: "OEE",
    colProduct: "Termék", colCycle: "Ciklus", colProduced: "Legyártott", colFtt: "FTT veszt.",
    colScrap: "Selejt", colDowntimeCodes: "Állásidő kódok", colDowntimeMin: "Állásidő perc",
    colOpenTime: "Nyitott idő", colTarget: "Cél", colFill: "Telj. %",
    total: "Összesen", fulfillment: "Teljesülés", cycleTime: "Ciklusidő",
    machineBreakdown: "Gépenkénti OEE", allMachines: "Összes gép",
    settings: "⚙ Műszak beállítás", shiftSchedule: "Műszak séma", shiftLength: "Műszak hossz",
    shiftsPerDay: "Műszak / nap", workingDays: "Munkanap / hét", plannedStop: "Tervezett állás / műszak",
    plannedStops: "Tervezett állások",
    summary: "Összesítés", shiftTotal: "Műszak összesen", plannedStopTotal: "Tervezett állás összesen",
    baseOpenTime: "Alap nyitott idő", days: "nap", shifts: "műszak",
    shiftCount: "Műszakszám", custom: "Egyedi (perc)",
    report: "📊 Riport", dailyReport: "Napi jelentés", productionReport: "Gyártási Riport",
    overallStatus: "Általános státusz", onTarget: "Célon", attention: "Figyelem", critical: "Kritikus",
    onTargetLines: "gép célon", belowLines: "gép elmaradásban", totalProduced: "Összes gyártott",
    plan: "Terv", planFulfillment: "Terv teljesítés", scrapRate: "selejt arány", perMachine: "perc/gép",
    linePerformance: "Gépsorok teljesítménye", line: "Gépsor", autoGenerated: "Automatikusan generált riport",
    licenseRequired: "Szerkesztői licenc szükséges",
    licenseDescription: "A nézők mindig ingyen látják a vizuált. Csak a szerkesztőknek kell licenc a beállítások módosításához.",
    startTrial: "30 napos ingyenes próba indítása"
};

const TABLE: Record<Language, Strings> = { en: EN, hu: HU };

export function t(language: Language, key: keyof Strings): string {
    return (TABLE[language] || EN)[key];
}
